name: test-rate-limiter
services:
  database:
    image: postgres:17-alpine3.22
    container_name: test-rate-limiter-database
    restart: unless-stopped
    volumes:
      - test-rate-limiter-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_DBNAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    container_name: test-rate-limiter-migrations
    depends_on:
      database:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=${DATABASE_HOST} port=${DATABASE_PORT} user=${DATABASE_USER} password=${DATABASE_PASS} dbname=${DATABASE_DBNAME}
    networks:
      - test-rate-limiter-network
    volumes:
      - ./../migrations:/migrations

  server:
    container_name: test-rate-limiter-server
    build:
      context: ./../
      dockerfile: ./build/app.Dockerfile
      target: final
    ports:
      - 80:80
    depends_on:
      database:
        condition: service_healthy
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: 80

      LOGGER_FILE: "" #set empty to improve performance
      LOGGER_LEVEL: "ERROR"

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_DBNAME: ${DATABASE_DBNAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    volumes:
      - type: bind
        source: ./../logs/test
        target: /logs
    networks:
      - test-rate-limiter-network

  # Контейнер с интеграционными тестами
  integration-tests:
    container_name: test-rate-limiter-integration
    profiles:
      - tests
    build:
      context: ./../
      dockerfile: ./build/integration.Dockerfile
    environment:
      API_HOST: http://server
      API_PORT: 80
      DATABASE_DSN: postgres://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DBNAME}?sslmode=disable
    depends_on:
      server:
        condition: service_started
        required: true
    networks:
      - test-rate-limiter-network

volumes:
  test-rate-limiter-db-data:
    name: test-rate-limiter-db-data
networks:
  test-rate-limiter-network:
    driver: bridge
